"""
App.py
This file will be auto-generated by code
"""
# Convert notebook to HTML and serve
from aiohttp import web
import nbformat
from nbconvert import HTMLExporter
from navconfig import BASE_DIR
from navconfig.logging import logging
from navigator.handlers.types import AppHandler
from querysource.services import QuerySource


logging.getLogger(name='traitlets').setLevel(logging.ERROR)


# list of Lab reports
LAB_DIR = BASE_DIR.joinpath('lab')
def get_reports():
    return [file for file in LAB_DIR.iterdir() if file.suffix == '.ipynb']


async def notebook_handler(request):
    notebook_name = request.match_info['name']
    notebook_path = LAB_DIR.joinpath(f'{notebook_name}.ipynb')

    if not notebook_path.exists():
        return web.Response(
            status=404,
            text="Notebook not found"
        )

    with open(notebook_path) as f:
        nb = nbformat.read(f, as_version=4)
        exporter = HTMLExporter()
        body, resources = exporter.from_notebook_node(nb)

    return web.Response(text=body, content_type='text/html')

class Main(AppHandler):
    """Main Class.
    Using this class as a boilerplate for starting new programs.
    """
    _middleware: list = []
    enable_static: bool = False
    enable_pgpool: bool = True
    enable_error_middleware: bool = False

    def configure(self):
        super(Main, self).configure()
        # version
        # Loading QUerySource
        qry = QuerySource(lazy=False, loop=self.event_loop())
        qry.setup(self.app)

        # Dynamically add routes for each notebook
        route_path = f'/reports/lab/{{name}}'
        self.app.router.add_get(route_path, notebook_handler)

    @classmethod
    def evt(cls):
        return cls.get_event_loop(cls)
