"""
App.py
This file will be auto-generated by code
"""
from navconfig.logging import logging
from navigator.handlers.types import AppHandler
from navigator_auth import AuthHandler
from querysource.services import QuerySource



logging.getLogger(name='traitlets').setLevel(logging.ERROR)

class Main(AppHandler):
    """Main Class.
    Using this class as a boilerplate for starting new programs.
    """
    _middleware: list = []
    enable_static: bool = False
    enable_pgpool: bool = True
    enable_error_middleware: bool = False

    def configure(self):
        super(Main, self).configure()
        # Loading QuerySource — no need to pass the event loop; it is captured
        # automatically from aiohttp's running loop on startup.
        qry = QuerySource(lazy=False)
        qry.setup(self.app)
        ### Auth System
        # create a new instance of Auth System
        auth = AuthHandler()
        auth.setup(self.app)  # configure this Auth system into App.

    @classmethod
    def evt(cls):
        return cls.get_event_loop(cls)
