"""
App.py
This file will be auto-generated by code
"""
from navconfig.logging import logging
from navigator.handlers.types import AppHandler
from querysource.services import QuerySource


logging.getLogger(name='traitlets').setLevel(logging.ERROR)

class Main(AppHandler):
    """Main Class.
    Using this class as a boilerplate for starting new programs.
    """
    _middleware: list = []
    enable_static: bool = False
    enable_pgpool: bool = True
    enable_error_middleware: bool = False

    def configure(self):
        super(Main, self).configure()
        # version
        # Loading QUerySource
        qry = QuerySource(
            lazy=False,
            loop=self.event_loop()
        )
        qry.setup(self.app)

    @classmethod
    def evt(cls):
        return cls.get_event_loop(cls)
