"""
App.py
This file will be auto-generated by code
"""
from navigator.handlers.types import AppHandler

class QS(AppHandler):
    """Main Class.
    Using this class as a boilerplate for starting new programs.
    """
    _middleware: list = []
    enable_static: bool = True
    enable_pgpool: bool = True
    enable_error_middleware: bool = False

    def configure(self):
        super(QS, self).configure()
